config/routes.rb
Ezra::Application.routes.draw do

  devise_for :user
  devise_scope :user do
    get "signin", to: "devise/sessions#new"
  end

  match '/users/manage/save' => 'users#manage_save', :as => :manage_save, :via => :post
  match '/users/manage/:id' => 'users#manage', :as => :manage, :via => :get
  match '/users/:id/recent' => 'users#recent', :as => :recent, :via => :get
  resources :users
  resources :targets
  resources :features
  match '/features/check_feature_uniqueness' => 'features#check_feature_uniqueness', :as => :feature_unique, :via => :post
  resources :hits
  match '/hits/:id/save_clip' => 'hits#save_clip', :as => :save_clip, :via => :post
  match '/hits/listen/:clip' => 'hits#listen', :as => :listen, :via => :get
  resources :activities, only: [:index]
  resources :statics, only: [:show]

  match '/:id', to: "statics#show"

  root to: 'statics#show', id: 'home'

end

app/models/hit.rb
# == Schema Information
#
# Table name: hits
#
#  id              :integer          not null, primary key
#  location        :float
#  confirmed       :integer
#  flagged         :boolean
#  audio_file      :string(255)
#  target_id       :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  transcript      :text
#  feat_vals       :text
#  window_start    :float
#  window_duration :float
#  notes           :text
#

class Hit < ActiveRecord::Base
  include PublicActivity::Common

  attr_accessible :audio_file, :confirmed, :flagged
  attr_accessible :location, :transcript, :feat_vals
  attr_accessible :window_start, :window_duration, :notes
  serialize :feat_vals, Hash

  belongs_to :target, :inverse_of => :hits
  has_many :features, :through => :target

  validates :audio_file, presence: true
  validates :confirmed, presence: true, numericality: { only_integer: true,
                                                        greater_than: -3,
                                                        less_than:     2 }
  validates :location, presence: true, numericality: { greater_than: 0 }
  validates :target_id, presence: true
  validates :window_start, numericality: { greater_than_or_equal_to: 0, }
  validates :window_duration, numericality: { greater_than: 0, }

end

app/models/target.rb
# == Schema Information
#
# Table name: targets
#
#  id         :integer          not null, primary key
#  phrase     :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Target < ActiveRecord::Base
  include PublicActivity::Common

  attr_accessible :phrase, :feature_ids
  belongs_to :user, :inverse_of => :targets
  has_and_belongs_to_many :features, uniq: true
  has_many :hits

  validates :user_id, presence: true
  validates :phrase, presence: true, length: { maximum: 30 }
  default_scope order: 'targets.created_at ASC'
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_user, only: [:new, :create, :edit, :update]

  # deferred in v1.0
#  before_filter :check_available_targets, only: [:show,:edit]

  def index   # GET /targets          -> targets_path
    @targets = Target.paginate(page: params[:page])
  end

  def show    # GET /targets/:id      -> target_path(target)
    @target = Target.find(params[:id])
    @user = current_user
    hits_params = params.slice(:confirmed, :flagged)
    if hits_params.has_key?(:flagged)
      hits_params[:flagged] = (hits_params[:flagged] == "true")
    end
    if hits_params.has_key?(:confirmed)
      @status = hits_params[:confirmed]
    end
    @hits = @target.hits.where(hits_params).paginate(page: params[:page])
    @features = @target.features
    phrase = @target.phrase.gsub(/ /,'_')
    @savedFiles = Dir.glob('public/clips/'+phrase+'/*.mp3')
  end

  def new     # GET /targets/new      -> new_target_path
    @target = Target.new
  end

  def create  # POST /targets         -> targets_path
    @target = current_user.targets.build(params[:target])
    if @target.save
      flash[:success] = "Target \"#{@target.phrase}\" created successfully."
      render 'show'
    else
      render 'new'
    end
  end

  def edit    # GET /targets/:id/edit -> edit_target_path(target)
    @target = Target.find(params[:id])
  end

  def update  # PUT /targets/1        -> target_path(target)
    @target = Target.find(params[:id])
    if @target.update_attributes(params[:target], user: @user)
      flash[:success] = "Update successful."
      redirect_to target_path(@target)
    else
      render 'edit'
    end
  end

  #def destroy # DELETE /targets/1     -> target_path(target)
  #end
  private

  def check_available_targets
    # current_user = User.new
    # stats = Stats.new
    # current_user.stats = stats
    if !current_user.stats.availableTargets.include?(params[:id]) && !current_user.stats.availableTargets.empty?
      flash[:notice] = "You are not authorized to edit this target"
      @targets = Target.paginate(page: params[:page])
      #redirect_to :action => 'index'
      render 'index'
    end
  end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/targets/_error_messages.html.erb
<% if @target.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@target.errors.count, "error") %>.
    </div>
    <ul>
    <% @target.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/targets/_target.html.erb
<tr>
  <td> <%= link_to target.id, target %> </td>
  <td> <%= link_to target.phrase, target %> </td>
  <td><%=  link_to target.hits.count, target, class: "tgt-total" %></td>
  <td>
  	<%=  link_to target.hits.where(confirmed: 1).count.to_s+" ("+target.hits.where('confirmed = ? AND flagged = ? ', 1, true).count.to_s+")",  target_path(target, { confirmed: 1 }),  class: "confirmed"  %>
  </td>
  <td>
  	<%=  link_to target.hits.where(confirmed: 0).count.to_s+" ("+target.hits.where('confirmed = ? AND flagged = ? ', 0, true).count.to_s+")",  target_path(target, { confirmed: 0 }),  class: "unconfirmed" %></td>
  <td><%=  link_to target.hits.where(confirmed: -1).count.to_s+" ("+target.hits.where('confirmed = ? AND flagged = ? ', -1, true).count.to_s+")", target_path(target, { confirmed: -1 }), class: "not-present" %></td>
  <td><%=  link_to target.hits.where(flagged: true).count, target_path(target, { flagged: true }), class: "flags"  %></td>
</tr>

app/views/targets/edit.html.erb
<% provide(:title, "Edit \"" + @target.phrase + "\"") %>
<h1> Update target "<%= @target.phrase %>"</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@target) do |f| %>
      <%= render 'error_messages' %>

      <%= f.label :phrase, "Phrase" %>
      <%= f.text_field :phrase %>
      
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>

      <%= f.select :feature_ids, Feature.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %>
    <% end %>
  </div>
</div>

app/views/targets/index.html.erb
<% provide(:title, "Targets") %>
<%= will_paginate %>
<h2>Targets</h2>
<table class="targets table tablesorter">
	<thead>
                <th>Id</th>
		<th>Name</th>
		<th>Total</th>
		<th>Confirmed</th>
		<th>Unconfirmed</th>
		<th>Not Present</th>
		<th>Flagged</th>
	</thead>
	<%= render @targets %>
</table>

<%= will_paginate %>

app/views/targets/show.html.erb
<% provide(:title, 'Target | ' + @target.phrase) %>
  <h2>
    <%= link_to(@target) do %>
    <%= @target.id %>. <%= @target.phrase %>
    <% end %>
    <%
    if @status
      case @status.to_i
      when 1
        concat raw "<span class='confirmed'>Confirmed</span>"
      when 0
        concat raw "<span class='unconfirmed'>Unconfirmed</span>"
      when -1
        concat raw "<span class='not-present'>Not Present</span>"
      when -2
        concat raw "<span class='duplicate'>Duplicate</span>"
      end
    end
    %>
  </h2>
  <% if @status %>
    Count: <%= @hits.where(:confirmed => @status.to_i).count %>
  <% end %>
  <% if !@status %>
  Total: <%= @hits.count %> <br/>
  Confirmed: <%= link_to @hits.where(:confirmed => 1).count, target_path(@target, { confirmed: 1 }), class: "confirmed"%><br/>
  Unconfirmed: <%= link_to @hits.where(:confirmed => 0).count, target_path(@target, { confirmed: 0 }), class: "unconfirmed"%> <br/>
  Not Present: <%= link_to @hits.where(:confirmed => -1).count, target_path(@target, { confirmed: -1 }), class: "not-present"%> </span>
  <% end %>
  <h3>Features </h3>
  <table class="table table-striped tablesorter">
    <thead>
      <th>Name</th>
      <th>Created by</th>
      <th>Number of targets</th>
      <th>Instructions</th>
    </thead>
    <%= render @features %>
  </table>
  <h3>Hits</h3>
  <%= will_paginate @hits %>
  <table class="table table-striped tablesorter" style="width: 50%">
    <thead>
      <th>Hit Number</th>
      <% if !@status %>
        <th>Status</th>
      <% end %>
      <th>Flagged</th>
    </thead>
    <% @hits.each do |hit| %>
      <tr>
        <td><a class="btn btn-mini" href="<%= edit_hit_path(hit) %>" style="margin-right: 10px; margin-top: -5px"><i class="icon-pencil"></i></a><%= link_to hit.id, hit %></td>
        <td>
          <%
          if !@status
            case hit.confirmed
            when 1
              concat raw "<span class='confirmed'>Confirmed</span>"
            when 0
              concat raw "<span class='unconfirmed'>Unconfirmed</span>"
            when -1
              concat raw "<span class='not-present'>Not Present</span>"
            when -2
              concat raw "<span class='duplicate'>Duplicate</span>"
            end
          end
          %>
        </td>
        <td>
          <%
            if hit.flagged
              concat 'Flagged'
            end
          %>
        </td>
      </tr>
    <% end  %>
  </table>
  <%= will_paginate @hits %>
<br />

<section>