config/routes.rb
Ezra::Application.routes.draw do

  devise_for :user
  devise_scope :user do
    get "signin", to: "devise/sessions#new"
  end

  match '/users/manage/save' => 'users#manage_save', :as => :manage_save, :via => :post
  match '/users/manage/:id' => 'users#manage', :as => :manage, :via => :get
  match '/users/:id/recent' => 'users#recent', :as => :recent, :via => :get
  resources :users
  resources :targets
  resources :features
  match '/features/check_feature_uniqueness' => 'features#check_feature_uniqueness', :as => :feature_unique, :via => :post
  resources :hits
  match '/hits/:id/save_clip' => 'hits#save_clip', :as => :save_clip, :via => :post
  match '/hits/listen/:clip' => 'hits#listen', :as => :listen, :via => :get
  resources :activities, only: [:index]
  resources :statics, only: [:show]

  match '/:id', to: "statics#show"

  root to: 'statics#show', id: 'home'

end

app/models/static.rb
# == Schema Information
#
# Table name: statics
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  content     :text
#  slug        :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  short_title :text
#  sort        :integer
#

class Static < ActiveRecord::Base
  extend FriendlyId
  attr_accessible :title, :short_title, :content, :slug, :sort
  friendly_id :slug, use: :slugged

  validates :title,       presence: true
  validates :short_title, presence: true
  validates :content,     presence: true
  validates :slug,        presence: true
  validates :sort,        presence: true

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  #before_filter :signed_in_user
  #before_filter :admin_user, only: [:new, :create, :edit, :update]

  #def index
  #  @statics = Static.all

  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @statics }
  #   end
  # end

  # GET /statics/1
  # GET /statics/1.json
  def show
    @static = Static.find_by_slug(params[:id])
    render 'public/404', status: 404 if @static.nil?
  end


  # GET /statics/new
  # GET /statics/new.json
  # def new
  #   @static = Static.new
  # end

  # GET /statics/1/edit
  # def edit
  #   @static = Static.find(params[:id])
  # end

  # POST /statics
  # POST /statics.json
  # def create
  #   @static = Static.new(params[:static])

  #   if @static.save
  #     flash[:success] = "Static page \"#{@static.title}\" created successfully."
  #     render 'show'
  #   else
  #     render 'new'
  #   end
  # end

  # PUT /statics/1
  # PUT /statics/1.json
  # def update
  #   @static = Static.find(params[:id])

  #   respond_to do |format|
  #     if @static.update_attributes(params[:static])
  #       format.html { redirect_to @static, notice: 'Static was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @static.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /statics/1
  # DELETE /statics/1.json
#   def destroy
#     @static = Static.find(params[:id])
#     @static.destroy

#     respond_to do |format|
#       format.html { redirect_to statics_url }
#       format.json { head :no_content }
#     end
#   end
end

app/helpers/statics_helper.rb
module StaticsHelper
  require 'redcarpet'
  def render_markdown(content)
    options = {
      hard_wrap: true,
      filter_html: true,
      autolink: true,
      no_intraemphasis: true}
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, options)
    markdown.render(content).html_safe
  end
end

app/views/statics/_form.html.erb
<%# form_for(@static) do |f| %>
  <% if @static.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static.errors.count, "error") %> prohibited this static from being saved:</h2>

      <ul>
      <% @static.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%# f.label :title %><br />
    <%# f.text_field :title %>
  </div>
  <div class="field">
    <%# f.label :content %><br />
    <%# f.text_area :content %>
  </div>
  <div class="field">
    <%# f.label :slug %><br />
    <%# f.text_field :slug %>
  </div>
  <div class="actions">
    <%# f.submit %>
  </div>
<%# end %>

app/views/statics/edit.html.erb
<h1>Editing static</h1>

<%= render 'form' %>

<%= link_to 'Show', @static %> |
<%# link_to 'Back', statics_path %>

app/views/statics/index.html.erb
<h1>Listing statics</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Slug</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @statics.each do |static| %>
  <tr>
    <td><%= static.title %></td>
    <td><%= static.content %></td>
    <td><%= static.slug %></td>
    <td><%= link_to 'Show', static %></td>
    <td><%= link_to 'Edit', edit_static_path(static) %></td>
    <td><%= link_to 'Destroy', static, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Static', new_static_path %>

app/views/statics/new.html.erb
<h1>New static</h1>

<%= render 'form' %>

<%# link_to 'Back', statics_path %>

app/views/statics/show.html.erb
<% provide(:title, @static.title.to_s) %>

<%= render_markdown(@static.content) %>