config/routes.rb
Ezra::Application.routes.draw do

  devise_for :user
  devise_scope :user do
    get "signin", to: "devise/sessions#new"
  end

  match '/users/manage/save' => 'users#manage_save', :as => :manage_save, :via => :post
  match '/users/manage/:id' => 'users#manage', :as => :manage, :via => :get
  match '/users/:id/recent' => 'users#recent', :as => :recent, :via => :get
  resources :users
  resources :targets
  resources :features
  match '/features/check_feature_uniqueness' => 'features#check_feature_uniqueness', :as => :feature_unique, :via => :post
  resources :hits
  match '/hits/:id/save_clip' => 'hits#save_clip', :as => :save_clip, :via => :post
  match '/hits/listen/:clip' => 'hits#listen', :as => :listen, :via => :get
  resources :activities, only: [:index]
  resources :statics, only: [:show]

  match '/:id', to: "statics#show"

  root to: 'statics#show', id: 'home'

end

app/views/layouts/_footer.html.erb
<div id="version">ezra <%= @version %></div>
<div id="updated_date">updated <%= @updated_date %></div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "ezra", root_path, class: "brand" %>
      <ul class="nav pull-right">
        <% if signed_in? %>
          <%= render 'layouts/signedin_header' %>
        <% else %>
          <%= render 'layouts/public_links' %>
        <li><%= link_to "Sign in",  new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_public_links.html.erb
<% @statics.each do |static| %>
<li><%= link_to static.short_title, static_path(static) %></li>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_signedin_header.html.erb
<% if current_user.admin? %>
  <li><%= link_to "Users", users_path %></li>
<% end %>
<li><%= link_to "Targets", targets_path %></li>
<li><%= link_to "Features", features_path %></li>
 <li class="dropdown">
   <a class="dropdown-toggle"
      data-toggle="dropdown"
      href="#">
     Public
     <b class="caret"></b>
   </a>
   <ul class="dropdown-menu">
<%= render 'layouts/public_links' %>
</ul>
</li>
<li><%= link_to current_user.username, user_path(current_user) %></li>
<li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="#holder">
    <%= render 'layouts/header' %>

    <div id="main" class="container">
      <% flash.each do |key, value| %>
        <%# devise adds a :timedout key that shouldn't be displayed %>
        <% if key != :timedout %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
    <footer class="footer">
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </footer>
  </div>
</body>
</html>